Repository taikoxyz/taiko-geth, pull requests merged in 2023-09, with the labels that each got.

#111 chore(taiko_genesis): add Alpha-5 genesis JSON
  core/taiko_genesis.go
  core/taiko_genesis/genesis_alloc.go
  core/taiko_genesis/jolnir.json
  params/config.go
  params/taiko_config.go
Labels: area.client, meta.alpha-5

#114 feat(txpool): check if `gasFeeCap` is zero
  core/txpool/validation.go
Labels: area.client, type.enhancement, meta.alpha-5

#115 feat(beacon): make `ExecutableData.Transactions` optional
  beacon/engine/gen_ed.go
  beacon/engine/types.go
Labels: area.client, meta.alpha-5

#116 fix(miner): fix empty transactions list check
  miner/taiko_worker.go
Labels: area.client

#118 chore(params): Typo
  params/config.go
Labels: area.client, meta.alpha-5

#119 feat(miner): improve `commitL2Transactions`
  miner/taiko_worker.go
Labels: area.client, type.enhancement

#120 feat(miner): improve `BuildTransactionsLists`
  miner/taiko_worker.go
Labels: area.client, type.enhancement

#121 fix(miner): send a singal to `payload.done` in `ResolveFull`
  miner/payload_building.go
Labels: area.client, meta.alpha-5
