Repository taikoxyz/taiko-geth, pull requests merged in 2024-07, with the labels that each got.

#282 fix(taiko_worker): fix a `maxBytesPerTxList` check issue
  miner/taiko_worker.go
Labels: type.bug

#275 chore(taiko): release 1.4.0
  CHANGELOG.md
Labels: autorelease: pending

#283 feat(taiko_miner): add `BuildTransactionsListsWithMinTip` method
  eth/taiko_api_backend.go
  miner/taiko_miner.go
  miner/taiko_worker.go
Labels: area.client

#284 chore(taiko): release 1.5.0
  CHANGELOG.md
Labels: autorelease: pending

#287 feat(core): introduce `BasefeeSharingPctg` in `BlockMetadata`
  beacon/engine/gen_blockmetadata.go
  beacon/engine/types.go
  core/state/statedb.go
  core/state_processor.go
  core/state_transition.go
  eth/catalyst/api.go
  miner/taiko_worker.go
Labels: area.client

#288 feat(taiko_genesis): update internal devnet genesis JSON for ontake hardfork
  core/taiko_genesis/internal_l2a.json
Labels: meta.alpha-n

#289 feat(consensus): update `ValidateAnchorTx`
  consensus/taiko/consensus.go
Labels: area.client

#290 feat(core): decode basefee params from `block.extraData`
  beacon/engine/gen_blockmetadata.go
  beacon/engine/types.go
  consensus/misc/eip1559/eip1559.go
  core/state/statedb.go
  core/state_processor.go
  core/state_transition.go
  core/taiko_genesis.go
  eth/catalyst/api.go
  miner/taiko_worker.go
  miner/worker.go
  params/config.go
Labels: meta.alpha-n

#291 feat(taiko_genesis): update interanl devnet genesis JSON for ontake hardfork
  core/taiko_genesis/internal_l2a.json
  miner/worker.go
Labels: meta.alpha-n

#292 feat(miner): improve `prepareWork()`
  miner/worker.go
Labels: area.client
