Repository taikoxyz/taiko-geth, pull requests merged in 2024-10, with the labels that each got.

#319 chore(taiko): release 1.10.0
  CHANGELOG.md
Labels: autorelease: pending

#330 feat(core): update `MainnetOntakeBlock`
  core/taiko_genesis.go
Labels: meta.alpha-n

#331 chore(taiko): release 1.11.0
  CHANGELOG.md
Labels: autorelease: pending

#334 chore(taiko): release 1.11.1
  CHANGELOG.md
Labels: autorelease: pending

#339 chore(main): add docker multi-arch image build
  .github/workflows/docker.yml
Labels: type.enhancement

#340 chore(ci): use `arc-runner-set`
  .github/workflows/ci.yml
  .github/workflows/close-inactive-issues.yml
  .github/workflows/lint-pr.yml
  .github/workflows/release-please.yml
Labels: type.enhancement

#341 chore(taiko_genesis): update genesis JSON
  core/taiko_genesis/internal_l2a.json
Labels: area.client
