Repository taikoxyz/taiko-geth, pull requests merged in 2024-06, with the labels that each got.

#264 feat(txpool): introduce `TAIKO_MIN_TIP` env
  core/txpool/validation.go
Labels: area.client

#265 chore(taiko): release 1.2.0
  CHANGELOG.md
Labels: autorelease: pending

#269 feat(miner): compress the txlist bytes after checking the transaction is executable
  miner/taiko_worker.go
Labels: area.client

#272 feat(miner): move `TAIKO_MIN_TIP` check to `commitL2Transactions`
  core/txpool/validation.go
  miner/taiko_worker.go
Labels: area.client

#271 chore(taiko): release 1.3.0
  CHANGELOG.md
Labels: autorelease: pending

#273 feat(miner): count last oversized transaction
  miner/taiko_worker.go
Labels: type.enhancement
