Repository taikoxyz/taiko-geth, pull requests merged in 2024-09, with the labels that each got.

#309 feat(core): update `ontakeForkHeight` to Sep 24, 2024
  core/taiko_genesis.go
Labels: meta.alpha-n

#310 chore(taiko): release 1.8.0
  CHANGELOG.md
Labels: autorelease: pending

#317 chore(taiko): release 1.9.0
  CHANGELOG.md
Labels: autorelease: pending

#322 fix(taiko_api): correct EstimatedGasUsed if lastTransaction is not null
  core/state/statedb.go
  miner/taiko_worker.go
Labels: type.bug

#323 feat(taiko_api): reduce the frequency of zlib compression when fetching txpool content
  miner/taiko_worker.go
  miner/taiko_worker_test.go
Labels: type.enhancement
