Repository taikoxyz/taiko-geth, pull requests merged in 2025-04, with the labels that each got.

#411 feat(miner): improve `pruneTransactions`
  miner/taiko_worker.go
Labels: area.client, type.enhancement

#409 chore(taiko): release 1.15.0
  .release-please-manifest.json
  CHANGELOG.md
Labels: autorelease: pending

#417 docs(taiko): autogen json-rpc docs
  .github/workflows/taiko-geth--pages.yml
  README.md
  scripts/taiko_generate_jsonrpc.go
Labels: type.enhancement

#423 chore(params): fix some comments
  params/config.go
Labels: meta.alpha-n
