Repository taikoxyz/taiko-geth, pull requests merged in 2025-05, with the labels that each got.

#424 chore(catalyst): increase `maxTrackedPayloads`
  eth/catalyst/queue.go
Labels: type.enhancement

#426 feat(rawdb): introduce `BuildPayloadArgsID` to `L1Origin`
  .github/workflows/ci.yml
  core/rawdb/gen_taiko_l1_origin.go
  core/rawdb/taiko_l1_origin.go
Labels: type.enhancement

#427 test(raw_db): add more `L1Origin` tests
  core/rawdb/taiko_l1_origin.go
  core/rawdb/taiko_l1_origin_test.go
Labels: type.enhancement

#428 feat(core): set `MainnetPacayaBlock`
  core/taiko_genesis.go
Labels: meta.alpha-n

#381 chore(taiko): update preconf devnet genesis jsons
  core/taiko_genesis.go
  core/taiko_genesis/genesis_alloc.go
  core/taiko_genesis/masaya.json
  core/taiko_genesis/preconf_devnet.json
  miner/taiko_worker.go
  params/taiko_config.go
  rpc/websocket.go
Labels: type.enhancement

#429 feat(miner): update logs in worker
  miner/taiko_worker.go
  rpc/websocket.go
Labels: type.enhancement

#430 feat(core): update `InternalDevnetPacayaBlock` to `0`
  core/taiko_genesis.go
Labels: area.client
