Repository taikoxyz/taiko-geth, pull requests merged in 2025-01, with the labels that each got.

#360 chore(taiko_genesis): update genesis JSONs
  core/taiko_genesis/internal_l2a.json
Labels: area.client

#342 feat(beacon): introduce soft blocks
  .github/workflows/docker.yml
  cmd/geth/config.go
  cmd/geth/main.go
  cmd/utils/taiko_flags.go
  consensus/taiko/consensus.go
  consensus/taiko/consensus_test.go
  core/blockchain.go
  core/rawdb/gen_taiko_l1_origin.go
  core/rawdb/taiko_l1_origin.go
  core/rawdb/taiko_l1_origin_test.go
  core/taiko_genesis.go
  core/taiko_genesis/genesis_alloc.go
  core/taiko_genesis/preconf_devnet.json
  eth/api_backend.go
  eth/backend.go
  eth/catalyst/api.go
  eth/ethconfig/config.go
  ethclient/taiko_api_test.go
  internal/ethapi/api.go
  internal/ethapi/api_test.go
  internal/ethapi/backend.go
  internal/ethapi/taiko_preconf.go
  internal/ethapi/transaction_args_test.go
  internal/flags/categories.go
  params/config.go
  params/taiko_config.go
Labels: area.client, meta.alpha-n, type.enhancement, option.do-not-merge

#366 feat(beacon): remove soft blocks implementation
  .github/workflows/docker.yml
  cmd/geth/main.go
  cmd/utils/taiko_flags.go
  consensus/taiko/consensus.go
  consensus/taiko/consensus_test.go
  core/blockchain.go
  core/rawdb/gen_taiko_l1_origin.go
  core/rawdb/taiko_l1_origin.go
  core/rawdb/taiko_l1_origin_test.go
  core/taiko_genesis.go
  core/taiko_genesis/genesis_alloc.go
  core/taiko_genesis/preconf_devnet.json
  eth/backend.go
  eth/catalyst/api.go
  eth/ethconfig/config.go
  ethclient/taiko_api_test.go
  internal/flags/categories.go
  params/config.go
  params/taiko_config.go
Labels: area.client

#374 fix(crypto): add IsOnCurve check (`go-ethereum` #31100)
  crypto/crypto.go
Labels: area.client

#346 chore(taiko): release 1.12.0
  CHANGELOG.md
Labels: autorelease: pending
