Repository taikoxyz/taiko-geth, pull requests merged in 2025-03, with the labels that each got.

#394 chore(core): revert `[]*ethapi.RPCTransaction` changes in miner
  miner/taiko_miner.go
  miner/taiko_worker.go
Labels: area.client

#389 chore(consensus): increase payload capacity
  eth/catalyst/queue.go
Labels: type.enhancement

#396 fix(eth): write `L1Origin` even if the payload is already in the cache
  eth/catalyst/api.go
Labels: area.client

#376 chore(taiko): release 1.13.0
  CHANGELOG.md
Labels: autorelease: pending

#397 chore(core): update Hekla Pacaya fork height
  core/taiko_genesis.go
Labels: meta.alpha-n

#401 chore(taiko): release 1.14.0
  .release-please-manifest.json
  CHANGELOG.md
Labels: autorelease: pending

#402 fix(repo): fix workflow to use configs
  .github/workflows/repo--release-please.yml
Labels: type.enhancement

#404 fix(taiko-client): fix an issue in `encodeAndCompressTxList`
  miner/taiko_worker.go
Labels: area.client

#403 chore(taiko): release 1.14.1
  .release-please-manifest.json
  CHANGELOG.md
Labels: autorelease: pending

#406 feat(miner): reduce the number compression attempts when fetching transactions list
  miner/taiko_worker.go
Labels: type.enhancement

#410 chore(eth): always use the latest block number for pending state in RPC calls
  eth/api_backend.go
  eth/api_debug.go
Labels: type.enhancement
