Repository taikoxyz/taiko-geth, pull requests merged in 2025-02, with the labels that each got.

#367 feat(eth): changes based on protocol `Pacaya` fork
  .github/workflows/docker.yml
  consensus/taiko/consensus.go
  consensus/taiko/consensus_test.go
  core/rawdb/gen_taiko_l1_origin.go
  core/rawdb/taiko_l1_origin.go
  core/taiko_genesis.go
  core/taiko_genesis/genesis_alloc.go
  core/taiko_genesis/internal_l2a.json
  core/taiko_genesis/preconf_devnet.json
  core/types/op_deposit_tx.go
  eth/catalyst/api.go
  eth/ethconfig/config.go
  eth/taiko_api_backend.go
  ethclient/taiko_api.go
  miner/payload_building.go
  params/config.go
  params/taiko_config.go
  params/taiko_config_test.go
  rpc/json.go
Labels: area.client, option.do-not-merge

#378 feat(consensus): introduce `AnchorV3GasLimit`
  consensus/taiko/consensus.go
  core/taiko_genesis.go
  params/config.go
Labels: meta.alpha-n, type.enhancement

#379 feat(consensus): update `TaikoAnchor.anchorV3` selector
  consensus/taiko/consensus.go
Labels: area.client, meta.alpha-n

#382 feat(taiko_genesis): update devnet genesis JSONs for new `AnchorV3` method
  core/taiko_genesis/internal_l2a.json
Labels: meta.alpha-n

#383 chore(taiko_genesis): update devnet genesis JSONs
  core/taiko_genesis/internal_l2a.json
Labels: meta.alpha-n

#387 fix(ethclient): remove useless l1Origin apis
  ethclient/taiko_api.go
Labels: area.client

#380 fix(consensus): avoid building repeat payload
  eth/catalyst/api.go
Labels: area.client, type.enhancement

#391 feat(miner): use `[]*ethapi.RPCTransaction` in RPC response body
  miner/taiko_miner.go
  miner/taiko_worker.go
Labels: area.client

#393 feat(core): align the upstream `types.Header`
  core/types/block.go
  core/types/gen_header_json.go
Labels: area.client
